apiVersion: v1
kind: Service
metadata:
  name: actual-budget
  namespace: home-ops
spec:
  selector:
    app.kubernetes.io/name: actual-budget
  ports:
    - name: http
      protocol: TCP
      port: 5006
      targetPort: 5006
